---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170602144934"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.1.162"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "demo9"
    - "featureName": "SpringBoot.Structure"

